version: '3'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=/run/secrets/nextcloud_postgres_database
      - POSTGRES_USER=/run/secrets/nextcloud_postgres_user
      - POSTGRES_PASSWORD=/run/secrets/nextcloud_postgres_password
    # secrets:
    #   # - nextcloud_postgres_root_password # hmmmm...necessary?
    #   - nextcloud_postgres_database
    #   - nextcloud_postgres_password
    #   - nextcloud_postgres_user 

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=/run/secrets/nextcloud_letsencrypt_virtualhost
      - LETSENCRYPT_HOST=/run/secrets/nextcloud_letsencrypt_host
      - LETSENCRYPT_EMAIL=/run/secrets/nextcloud_letsencrypt_email
      - POSTGRES_HOST=db
    # env_file:
    #   - db.env
    depends_on:
      - db
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  # secrets:
  #   nextcloud_postgres_root_password:
  #     external: true
  #   nextcloud_postgres_database:
  #     external: true
  #   nextcloud_postgres_password:
  #     external: true
  #   nextcloud_postgres_user:
  #     external: true
  #   nextcloud_letsencrypt_virtualhost:
  #     external: true
  #   nextcloud_letsencrypt_host:
  #     external: true
  #   nextcloud_letsencrypt_email:
  #     external: true

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
